### ISSUE TITLE
Incorrectly invoking Async methods from Shares\Program.cs

### ISSUE THREAD

**Issue by MarkMichaelis** [IntelliTect/EssentialCSharp#119]
When running `Shared\Program.cs` from any project (the launcher that calls each source file, the invocation doesn't wait for an async method to complete.

Line [Shared\Program.cs (93)](https://github.com/IntelliTect/EssentialCSharp/blob/v8.0/src/Shared/Program.cs#L93) checks for an `STAThreadAttribute` but neglects to check for the `System.Runtime.CompilerServices.AsyncStateMachineAttribute`.  When this attribute exists, the `InvokeMethodUsingReflection()` method needs to wait for the result (handling `Task`, `Task<T>`, `ValueTask<T>`, and `IAsyncEnumerable<T>` returns.  See line [67](https://github.com/IntelliTect/EssentialCSharp/blob/v8.0/src/Shared/Program.cs#L67)

**Comment by BenjaminMichaelis** [comment]
Seems to be solved
