### ISSUE TITLE
the Chapter18 folder has 2 "Listing 18.11" files, but not has "Listing18.10" file

### ISSUE THREAD

**Issue by zengjiapei3000** [IntelliTect/EssentialCSharp#130]
![Screenshot_2020-10-06 IntelliTect EssentialCSharp](https://user-images.githubusercontent.com/41148275/95153168-63d63f80-07c1-11eb-93c7-8ccac385a747.png)
Here is my screenshot.

**Comment by BenjaminMichaelis** [comment]
@zengjiapei3000 I have added the 18.10 code listing into the v7.0 branch. Thank you for pointing this out. You can view it here: 
https://github.com/IntelliTect/EssentialCSharp/commit/50a3a9909f93a6f51a3be57b7080794c370e86e7
 or pull from the latest version on v7.0.
