### ISSUE TITLE
What about last version support? 

### ISSUE THREAD

**Issue by theundergroundsorcerer** [IntelliTect/EssentialCSharp#131]
It seems, that both book site and this code support only previous edition of the book. 
Also, not sure it is the right place, but some supplemental on Span<T> and Memory<T> would be nice.

**Comment by twofingerrightclick** [comment]
Hello @theundergroundsorcerer ,

Are you looking for C# 8 listing example code? If so it's under the [C# Version 8 Branch ](https://github.com/IntelliTect/EssentialCSharp/tree/v8.0) . Currently the main branch is set to Version 7 still.

**Comment by MarkMichaelis** [comment]
Hi @theundergroundsorcerer,
Thanks for pointing this out. While the v8.0 code was there in a different branch, it should be the default branch. I have made the change accordingly.
Thanks,
Mark

**Comment by MarkMichaelis** [comment]
Regarding `Span` and `Memory`: I will write something about that too and post some code.  
Thanks for the feedback.  As no doubt you are aware, it takes an incredible amount of work to put out a book like this and I sincerely appreciate the constructive feedback.
