### ISSUE TITLE
Listing05.19.CountingLinesUsingOverloading had a test error

### ISSUE THREAD

**Issue by SinnoSong** [IntelliTect/EssentialCSharp#132]
DirectoryCountLines(subdirectory) called the DirectoryCountLines(string directory),this method will counting lines with ".cs" extension,but if i called DirectoryCountLines(string directory, string extension) ,it's mean i want to counting lines with the string "extension" rather than "*.cs"
![uTools_1609746006521](https://user-images.githubusercontent.com/59649274/103513169-f7231d80-4e61-11eb-8848-ee0eb64a91f9.png)

**Comment by BenjaminMichaelis** [comment]
Sorry for the slow reply @SinnoSong, after reading this, I am unclear on your question, do you mind clarifying your question?

**Comment by SinnoSong** [comment]
> Sorry for the slow reply @SinnoSong, after reading this, I am unclear on your question, do you mind clarifying your question?

I had test again，this method is ok.thank you.
