### ISSUE TITLE
Run the .NET Portability Analyzer Against the Code

### ISSUE THREAD

**Issue by MarkMichaelis** [IntelliTect/EssentialCSharp#15]
Thanks to @jaspet, we are compiling and executing the tests on Linux (and almost on Mac), I doubt there are any issues but it would be great if we could run the .NET Portability Analyzer against the entire code base and see what shows up.  

Ideally, this task would include adding execution of this analyzer to the build.

**Comment by BenjaminMichaelis** [comment]
This is tool is outdated and I think this is no longer an issue.
