### ISSUE TITLE
Restructuring to Eliminate "ChapterMain()"

### ISSUE THREAD

**Issue by MarkMichaelis** [IntelliTect/EssentialCSharp#16]
Somewhere in the conversion, each listing was changed so that:
- the listing files used `ChapterMain` rather than `Main` 
- Referenced a new project Called `SharedCode` rather than just linking to the necessary files in the Shared folder when required

At the time this was done (during `project.json`), I suspect it wasn`t possible to have two static `Main` methods and be able to disambiguate which ones to use as the entry point via the `StartupObject` property element.  Going forward, this is not a satisfactory solution, however.

I would like to request a restructuring as follows:

- [x] - Remove the reference to the "SharedCode" project
- [x] - Delete the `SharedCode` project
- [x] - Add "linked" files that point to the Program.cs file in the `Shared` directory
- [x] - Add "liked" files that point to the other files in the `Shared` directory as needed (i.e. PI Calculator in the threading listings.
- [x] - Add the following to CSProj tiles to disambiguate which Main to use in startup.
`          <PropertyGroup>
               <StartupObject>AddisonWesley.Michaelis.EssentialCSharp.Shared.Program</StartupObject>
          </PropertyGroup>`
- [x] - Rename all ChapterMain methods to Main (consider doing this via a mass search and replace.
- [x] - Verify dotnet build and dotnet test work from the command line
- [x] - Verify dotnet test works from the command line.
- [x] - Verify build/test works from VS2017
- [x] - If a mass/automated search and replace is performed, please verify that all files stay recognizable to Git as UTF8 files.

It is acceptable if this is done one project at a time rather than with a PowerShell/batch file just as long as it is clearly recorded which projects are done and which need work. 

Thoughts? Questions? Volunteers? :)

**Comment by nlundby** [comment]
Everything should be completed as you requested.  I ran the tests and get the same errors pre vs post restructuring, so I'm hoping I put it back together correctly.  I'm going to sleep on it before submitting the pull request, but its current state is on my branch https://github.com/nlundby/EssentialCSharp/tree/v7.0

**Comment by MarkMichaelis** [comment]
Wow Neal... that was fast. Thanks!

Can you please identify what tests are failing for you. On Windows, all the tests are passing for me. Thanks!

**Comment by nlundby** [comment]
Pull request submitted.  These two tests were failing for me on both Mac and Windows: 

Listing15.14.Tests.cs(31,57): error CS1501: No overload for method 'ExpectLike' takes 3 arguments [./EssentialCSharp/src/Chapter15.Tests/Chapter15.Tests.csproj]
Listing14.12.ProjectionWithSystem.Linq.Enumerable.Select.Tests.cs(40,36): error CS1501: No overload for method 'IsLike' takes 2 arguments [./src/Chapter14.Tests/Chapter14.Tests.csproj]

A fix was submitted in my pull request.

**Comment by MarkMichaelis** [comment]
Is it possible that you haven't updated your sub modules so you have and old version of test too,s by chance? (Or, alternatively, I didn't update the sub module pointer to point to the most recent TestTools perhaps?)

**Comment by nlundby** [comment]
Bingo!  All is well.  Yes, I believe the submodule pointer does not point to the most recent TestTools.  I added some steps to the Readme to ensure the latest are downloaded.  Unfortunately this did not resolve the mac(and now verified linux) test fail on listing08.16.

My 15.14 and 14.12 changes have been retracted in the pull request.

**Comment by COsborn2** [comment]
From the comments and looking at the current state of the code it sounds like a PR was made against this and these changes are live.
