### ISSUE TITLE
Provide Implementation of Listing 20.20 that works on MAC and/or Linux

### ISSUE THREAD

**Issue by MarkMichaelis** [IntelliTect/EssentialCSharp#18]
Unfortunately, [Listing 20.20](https://github.com/IntelliTect/EssentialCSharp/blob/v7.0/src/Chapter20/Listing20.20.DesignatingABlockForUnsafeCode.cs) only works on Windows.  It would be great to have the equivalent code on Linux and Mac.  

I have marked it as "High Priority" in the hopes that we can have an implementation before we publish the book so that I still have time to modify the text.

If you take this on, create an issue for the platform you are implementing and modify this issue to refer to the remaining one.

**Comment by nlundby** [comment]
I'll take a look and play with it.

Also,
Listing08.16 **Test** fails on Mac, but  builds successfully.  Attached are the test results windows vs Mac.  I believe this forum may have some leads on why, I don't 100% understand the code so I can't say for sure.

https://forums.xamarin.com/discussion/90684/set-file-to-hidden
[Listing08.16_TestResults.txt](https://github.com/IntelliTect/EssentialCSharp/files/1168642/Listing08.16_TestResults.txt)

**Comment by COsborn2** [comment]
I believe this is now listing 09.16. It looks like this test was updated to support Linux support. Mac OS support is *not* currently in, but adding the MacOS system flag like was done with Linux should solve the problem. This would require a code listing update.
