### ISSUE TITLE
Seems to have four virtual methods for Object, not three

### ISSUE THREAD

**Issue by jenramac** [IntelliTect/EssentialCSharp#23]
Hello,

In Essential C# 6.0, page 321 : "... programmers can override one or more of the **three** virtual methods. Chapter 9...."

It seems, there is four virtual methods for Object, like in table 6.2.

Have a nice day.

**Comment by Keboo** [comment]
Hi @jenramac though there are four virtual methods, only three of them can be overridden. If you attempt to override the Finalize method you will get [a compile error](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0249) telling you to provide a destructor instead.
You can find more information on this in the Resource Cleanup section (page 421-423).

**Comment by jenramac** [comment]
Hi @Keboo, I now see what you say. Have a nice day.
