### ISSUE TITLE
Minor uncorrect statement about nullability check in Table 4.4 (page 156 book)

### ISSUE THREAD

**Issue by brucegomes** [IntelliTect/EssentialCSharp#240]
![Screen Shot 2022-02-14 at 12 42 53 AM](https://user-images.githubusercontent.com/16536254/153829497-42853571-9777-4618-aed7-d3f2d1c10318.png)

Table 4.4 states:
> `is { } will issue a warning` if you check for not null with a non-nullable value type (such as int).

I believe this is not correct, and also it contradicts the next page statement that says:
> Lastly, property pattern matching (C# 8.0) with is { } will check for not null; however, but unlike using is object, `it won’t report a warning` when checking for not null on a non-nullable type.

- also, the part `however, but` could be omitted and simplify the sentence 

the below pic illustrates how `is {}` does not get flagged as a warning

![MicrosoftTeams-image](https://user-images.githubusercontent.com/16536254/153830883-f8aa567a-7a4b-45c0-a43b-50fabebe9a9a.png)

**Comment by BenjaminMichaelis** [comment]
Thanks for the feedback! I appreciate the screenshots to help explain what you found! I totally agree this is confusing and appears like contradictory statements.
```
int text = 0;
if (text is object)
{
    System.Console.WriteLine("text is object");
}
if ((text is { }))
{
    System.Console.WriteLine("text is { }");
}
else // ((text is null))
{
    System.Console.WriteLine("text is null");
}
```

You are correct that `text is object` gives warning [CS0183](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0183?f1url=%3FappId%3Droslyn%26k%3Dk(CS0183)) while `text is { }` has none. 

Thank you for bringing this up! I will go and clarify the text on this!

**Comment by BenjaminMichaelis** [comment]
@MarkMichaelis if you would check the changes in chapter 4 of the manuscript for these changes that would be great
