### ISSUE TITLE
Refactor to access modifier, static, then return type

### ISSUE THREAD

**Issue by BenjaminMichaelis** [IntelliTect/EssentialCSharp#262]
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/22186029/163492328-9ca7a00b-d139-407d-a7d1-dd71ee8a9889.png)
In 6.36 we have static public string instead of public static string;

Which ordering do we want to make consistent? Right now typically I see is access specifier then static, then return value, then name.

**Comment by BenjaminMichaelis** [comment]
This needs to be done in one big refactoring

**Comment by Keboo** [comment]
I would propose we go with access modifier first to avoid running afoul of [IDE0036](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0036) messages showing in tools.
