### ISSUE TITLE
15.5, 15.9 and 15.18  Code

### ISSUE THREAD

**Issue by HannaMichaelis** [IntelliTect/EssentialCSharp#278]
The code for 15.5 is pretty different from what it is in the book. Mark already worked on it a bit but it needs further changes

**Comment by HannaMichaelis** [comment]
15.9 and 15.18 are both wildly different than the book, they need further review

**Comment by BenjaminMichaelis** [comment]
Is this all fixed now @HannaMichaelis ?

**Comment by HannaMichaelis** [comment]
I can't tell, what branch would I have to be on in gitkraken to see it?

**Comment by HannaMichaelis** [comment]
I don't think it is

**Comment by BenjaminMichaelis** [comment]
> I can't tell, what branch would I have to be on in gitkraken to see it?

It should be in main

**Comment by HannaMichaelis** [comment]
Ok, I can't see any changes to it

**Comment by BenjaminMichaelis** [comment]
Looks good as of now
