### ISSUE TITLE
13.24 Code

### ISSUE THREAD

**Issue by HannaMichaelis** [IntelliTect/EssentialCSharp#279]
In the book 13.24 includes arrows, I think it's an image so the code in visual studios is formatted differently and won't appear the same on the pdf.

**Comment by BenjaminMichaelis** [comment]
Is this all fixed now @HannaMichaelis ?

**Comment by HannaMichaelis** [comment]
Maybe? It was more a decision that had to be made of whether or not it should be an image or code. I don't know what it's ultimately supposed to look like so I don't know.
