### ISSUE TITLE
Zip file download from github doesn't build due to missing submodule

### ISSUE THREAD

**Issue by MarkMichaelis** [IntelliTect/EssentialCSharp#30]
After downloading the source code zip from github (not using a clone), the project fails to build with the following error:
`C:\Program Files\dotnet\sdk\2.1.202\NuGet.targets(239,5): error MSB3202: not found project file“C:\Users\...\Documents\EC\submodules\TestTools\IntelliTect.TestTools.Console\IntelliTect.TestTools.Console.csproj”。 [C:\Users\...\Documents\EC\EssentialCSharp.sln]`

**Comment by COsborn2** [comment]
Submodule references are removed in the current version of the sln. This issue should be resolved
