### ISSUE TITLE
Rename v9.0 Branch?

### ISSUE THREAD

**Issue by MarkMichaelis** [IntelliTect/EssentialCSharp#369]
Chapter 1 has been updated for C# 11.  I expect this will happen in other cases too.  Should we rename the v9.0 branch?

**Comment by BenjaminMichaelis** [comment]
Up to you I would say! Depends I guess if you are writing all the way to 11 or are writing for 9.0 and going to have to go through the content a few times I would assume. We have to update some pipelines simultaneously though if we change this

**Comment by BenjaminMichaelis** [comment]
Done
