### ISSUE TITLE
Add support for method filtering to ...\src\Shared\Tests\CompilerAssert.cs

### ISSUE THREAD

**Issue by MarkMichaelis** [IntelliTect/EssentialCSharp#430]
Delete the `...\src\Shared\CompilerAssert.cs` file and change references to use `...\src\Shared\Tests\CompilerAssert.cs`. This will require adding support into `CompilerAssert.CompileAsync` to include a target method parameter that only compiles the code (or only returns diagnostics) within the method specified.

**Comment by BenjaminMichaelis** [comment]
Should be fixed with #475
