### ISSUE TITLE
Review Changes Chapter 18

### ISSUE THREAD

**Issue by MarkMichaelis** [IntelliTect/EssentialCSharp#549]
Please review the changes in Chapter 18 (Generic attributes and Caller* attributes)

**Comment by Keboo** [comment]
Done. Comments and feedback provided.

**Comment by MarkMichaelis** [comment]
Changes processed. Please review again.

**Comment by BenjaminMichaelis** [comment]
Can this be closed @MarkMichaelis @Keboo or is there things remaining?

**Comment by Keboo** [comment]
Yea I think so. There is only one comment in the document, but this ticket is done.
