### ISSUE TITLE
Wrong statement about operator precedence

### ISSUE THREAD

**Issue by della-90** [IntelliTect/EssentialCSharp#8]
Hi,

At page 121, there's the following statement:

>     if ((hourOfTheDay > 23) || (hourOfTheDay < 0))
> [...]
> Note that the parentheses are not necessary here; the logical operators are of ~~higher precedence~~ than the relational operators

Actually logical operators have a **lower precedence** than relational operators, because otherwise `hourOfTheDay > 23 || hourOfTheDay < 0` would be equivalent to `hourOfTheDay > (23 || hourOfTheDay) < 0`, which obviously results in a compile error.

**Comment by MarkMichaelis** [comment]
Thanks... I am delving into this chapter within the next month and will review this in detail then.  Thanks very much for posting.

**Comment by della-90** [comment]
You're welcome! It's nice to give my little contribution to such a great book!

**Comment by COsborn2** [comment]
I can't find a similar statement in my version of the book, so Im going to assume this issue has been resolved.

**Comment by COsborn2** [comment]
This error is present on Page140 in my version of the book.
